import { ElementRef, OnInit, Renderer2 } from '@angular/core';
export declare class CalendarComponent implements OnInit {
    private eRef;
    private renderer;
    monthString: string;
    targetString: string;
    type: string;
    dp: any;
    prev: any;
    next: any;
    grid: any;
    buttonShow: any;
    tbody: any;
    target: any;
    monthNames: string[];
    dayNames: string[];
    dateObj: Date;
    curYear: number;
    year: number;
    curMonth: number;
    month: number;
    currentDate: boolean;
    keys: {
        [name: string]: any;
    };
    date: number;
    bModal: boolean;
    constructor(eRef: ElementRef, renderer: Renderer2);
    ngOnInit(): void;
    datepicker(modal: boolean): void;
    checkDateInput(): boolean;
    bindHandlers(): void;
    handleGridBlur(): boolean;
    handleGridFocus(): boolean;
    handleGridKeyPress(e: any): boolean;
    handleGridClick(id: any, e: any): boolean;
    addEventListenerList(thisobj: any): void;
    handlePrevClick(e: any): boolean;
    handleNextClick(e: any): boolean;
    handlePrevKeyDown(e: any): boolean;
    handleNextKeyDown(e: any): boolean;
    showDlg(): void;
    showDialogMethod(e: any): boolean;
    handleGridKeyDown(e: any): boolean;
    clickedOutside(event: any): void;
    hideDlg(): void;
    showPrevMonth(offset: any): void;
    showNextMonth(offset: any): void;
    showPrevYear(): void;
    showNextYear(): void;
    fillGrid(): void;
    calcNumDays(year: any, month: any): number;
    calcStarWeekDay(year: any, month: any): number;
}
